package pe.gob.inei.sistencuesta;

// Generated 13/09/2013 09:04:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Capitulo generated by hbm2java
 */
@Entity
@Table(name = "capitulo", catalog = "bd_sistencuesta")
public class Capitulo implements java.io.Serializable {

	private Integer codigoCapitulo;
	private Cuestionario cuestionario;
	private int numero;
	private String titulo;
	private Set<Pregunta> preguntas = new HashSet<Pregunta>(0);

	public Capitulo() {
	}

	public Capitulo(Cuestionario cuestionario, int numero, String titulo) {
		this.cuestionario = cuestionario;
		this.numero = numero;
		this.titulo = titulo;
	}

	public Capitulo(Cuestionario cuestionario, int numero, String titulo,
			Set<Pregunta> preguntas) {
		this.cuestionario = cuestionario;
		this.numero = numero;
		this.titulo = titulo;
		this.preguntas = preguntas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoCapitulo", unique = true, nullable = false)
	public Integer getCodigoCapitulo() {
		return this.codigoCapitulo;
	}

	public void setCodigoCapitulo(Integer codigoCapitulo) {
		this.codigoCapitulo = codigoCapitulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoCuestionario", nullable = false)
	public Cuestionario getCuestionario() {
		return this.cuestionario;
	}

	public void setCuestionario(Cuestionario cuestionario) {
		this.cuestionario = cuestionario;
	}

	@Column(name = "Numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "Titulo", nullable = false, length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capitulo")
	public Set<Pregunta> getPreguntas() {
		return this.preguntas;
	}

	public void setPreguntas(Set<Pregunta> preguntas) {
		this.preguntas = preguntas;
	}

}
