package pe.gob.inei.sistencuesta;

// Generated 17/09/2013 09:30:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "bd_sistencuesta")
public class Categoria implements java.io.Serializable {

	private Integer codigoCategoria;
	private String nombre;
	private Set<Cuestionario> cuestionarios = new HashSet<Cuestionario>(0);
	private Set<Pregunta> preguntas = new HashSet<Pregunta>(0);

	public Categoria() {
	}

	public Categoria(String nombre) {
		this.nombre = nombre;
	}

	public Categoria(String nombre, Set<Cuestionario> cuestionarios,
			Set<Pregunta> preguntas) {
		this.nombre = nombre;
		this.cuestionarios = cuestionarios;
		this.preguntas = preguntas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoCategoria", unique = true, nullable = false)
	public Integer getCodigoCategoria() {
		return this.codigoCategoria;
	}

	public void setCodigoCategoria(Integer codigoCategoria) {
		this.codigoCategoria = codigoCategoria;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Cuestionario> getCuestionarios() {
		return this.cuestionarios;
	}

	public void setCuestionarios(Set<Cuestionario> cuestionarios) {
		this.cuestionarios = cuestionarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Pregunta> getPreguntas() {
		return this.preguntas;
	}

	public void setPreguntas(Set<Pregunta> preguntas) {
		this.preguntas = preguntas;
	}

}
