package pe.gob.inei.sistencuesta;

// Generated 15/09/2013 10:46:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cedula generated by hbm2java
 */
@Entity
@Table(name = "cedula", catalog = "bd_sistencuesta")
public class Cedula implements java.io.Serializable {

	private Integer codigoCedula;
	private Personal personal;
	private Cuestionario cuestionario;
	private Usuario usuario;
	private Ruta ruta;
	private String numeroCedula;
	private String fecharegistro;
	private String referenciaGeografica;
	private byte[] imagenLugar;
	private char estado;
	private Set<CedulaRespuesta> cedulaRespuestas = new HashSet<CedulaRespuesta>(
			0);

	public Cedula() {
	}

	public Cedula(Cuestionario cuestionario, Usuario usuario, Ruta ruta,
			String numeroCedula, String referenciaGeografica, char estado) {
		this.cuestionario = cuestionario;
		this.usuario = usuario;
		this.ruta = ruta;
		this.numeroCedula = numeroCedula;
		this.referenciaGeografica = referenciaGeografica;
		this.estado = estado;
	}

	public Cedula(Personal personal, Cuestionario cuestionario,
			Usuario usuario, Ruta ruta, String numeroCedula,
			String fecharegistro, String referenciaGeografica,
			byte[] imagenLugar, char estado,
			Set<CedulaRespuesta> cedulaRespuestas) {
		this.personal = personal;
		this.cuestionario = cuestionario;
		this.usuario = usuario;
		this.ruta = ruta;
		this.numeroCedula = numeroCedula;
		this.fecharegistro = fecharegistro;
		this.referenciaGeografica = referenciaGeografica;
		this.imagenLugar = imagenLugar;
		this.estado = estado;
		this.cedulaRespuestas = cedulaRespuestas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoCedula", unique = true, nullable = false)
	public Integer getCodigoCedula() {
		return this.codigoCedula;
	}

	public void setCodigoCedula(Integer codigoCedula) {
		this.codigoCedula = codigoCedula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoPersonal")
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoCuestionario", nullable = false)
	public Cuestionario getCuestionario() {
		return this.cuestionario;
	}

	public void setCuestionario(Cuestionario cuestionario) {
		this.cuestionario = cuestionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoRuta", nullable = false)
	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	@Column(name = "NumeroCedula", nullable = false, length = 15)
	public String getNumeroCedula() {
		return this.numeroCedula;
	}

	public void setNumeroCedula(String numeroCedula) {
		this.numeroCedula = numeroCedula;
	}

	@Column(name = "fecharegistro", length = 10)
	public String getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(String fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "ReferenciaGeografica", nullable = false, length = 100)
	public String getReferenciaGeografica() {
		return this.referenciaGeografica;
	}

	public void setReferenciaGeografica(String referenciaGeografica) {
		this.referenciaGeografica = referenciaGeografica;
	}

	@Column(name = "ImagenLugar")
	public byte[] getImagenLugar() {
		return this.imagenLugar;
	}

	public void setImagenLugar(byte[] imagenLugar) {
		this.imagenLugar = imagenLugar;
	}

	@Column(name = "Estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cedula")
	public Set<CedulaRespuesta> getCedulaRespuestas() {
		return this.cedulaRespuestas;
	}

	public void setCedulaRespuestas(Set<CedulaRespuesta> cedulaRespuestas) {
		this.cedulaRespuestas = cedulaRespuestas;
	}

}
