package pe.gob.inei.sistencuesta;

// Generated 17/09/2013 09:30:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CedulaRespuesta generated by hbm2java
 */
@Entity
@Table(name = "cedula_respuesta", catalog = "bd_sistencuesta")
public class CedulaRespuesta implements java.io.Serializable {

	private Integer codigoCedulaRespuesta;
	private Pregunta pregunta;
	private Cedula cedula;
	private Respuesta respuesta;
	private String respuesta_1;
	private Set<Inconsistencia> inconsistencias = new HashSet<Inconsistencia>(0);

	public CedulaRespuesta() {
	}

	public CedulaRespuesta(Pregunta pregunta, Cedula cedula, String respuesta_1) {
		this.pregunta = pregunta;
		this.cedula = cedula;
		this.respuesta_1 = respuesta_1;
	}

	public CedulaRespuesta(Pregunta pregunta, Cedula cedula,
			Respuesta respuesta, String respuesta_1,
			Set<Inconsistencia> inconsistencias) {
		this.pregunta = pregunta;
		this.cedula = cedula;
		this.respuesta = respuesta;
		this.respuesta_1 = respuesta_1;
		this.inconsistencias = inconsistencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoCedulaRespuesta", unique = true, nullable = false)
	public Integer getCodigoCedulaRespuesta() {
		return this.codigoCedulaRespuesta;
	}

	public void setCodigoCedulaRespuesta(Integer codigoCedulaRespuesta) {
		this.codigoCedulaRespuesta = codigoCedulaRespuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoPregunta", nullable = false)
	public Pregunta getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(Pregunta pregunta) {
		this.pregunta = pregunta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoCedula", nullable = false)
	public Cedula getCedula() {
		return this.cedula;
	}

	public void setCedula(Cedula cedula) {
		this.cedula = cedula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoRespuesta")
	public Respuesta getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(Respuesta respuesta) {
		this.respuesta = respuesta;
	}

	@Column(name = "Respuesta", nullable = false, length = 1000)
	public String getRespuesta_1() {
		return this.respuesta_1;
	}

	public void setRespuesta_1(String respuesta_1) {
		this.respuesta_1 = respuesta_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cedulaRespuesta")
	public Set<Inconsistencia> getInconsistencias() {
		return this.inconsistencias;
	}

	public void setInconsistencias(Set<Inconsistencia> inconsistencias) {
		this.inconsistencias = inconsistencias;
	}

}
