package pe.gob.inei.sistencuesta;

// Generated 12/09/2013 09:31:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name = "opcion", catalog = "bd_sistencuesta")
public class Opcion implements java.io.Serializable {

	private Integer codigoOpcion;
	private String nombre;
	private Set<Acceso> accesos = new HashSet<Acceso>(0);

	public Opcion() {
	}

	public Opcion(String nombre) {
		this.nombre = nombre;
	}

	public Opcion(String nombre, Set<Acceso> accesos) {
		this.nombre = nombre;
		this.accesos = accesos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoOpcion", unique = true, nullable = false)
	public Integer getCodigoOpcion() {
		return this.codigoOpcion;
	}

	public void setCodigoOpcion(Integer codigoOpcion) {
		this.codigoOpcion = codigoOpcion;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<Acceso> getAccesos() {
		return this.accesos;
	}

	public void setAccesos(Set<Acceso> accesos) {
		this.accesos = accesos;
	}

}
