package pe.gob.inei.sistencuesta;

// Generated 13/09/2013 09:04:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RutaPersonalId generated by hbm2java
 */
@Embeddable
public class RutaPersonalId implements java.io.Serializable {

	private int codigoPersonal;
	private int codigoRuta;

	public RutaPersonalId() {
	}

	public RutaPersonalId(int codigoPersonal, int codigoRuta) {
		this.codigoPersonal = codigoPersonal;
		this.codigoRuta = codigoRuta;
	}

	@Column(name = "CodigoPersonal", nullable = false)
	public int getCodigoPersonal() {
		return this.codigoPersonal;
	}

	public void setCodigoPersonal(int codigoPersonal) {
		this.codigoPersonal = codigoPersonal;
	}

	@Column(name = "CodigoRuta", nullable = false)
	public int getCodigoRuta() {
		return this.codigoRuta;
	}

	public void setCodigoRuta(int codigoRuta) {
		this.codigoRuta = codigoRuta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RutaPersonalId))
			return false;
		RutaPersonalId castOther = (RutaPersonalId) other;

		return (this.getCodigoPersonal() == castOther.getCodigoPersonal())
				&& (this.getCodigoRuta() == castOther.getCodigoRuta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoPersonal();
		result = 37 * result + this.getCodigoRuta();
		return result;
	}

}
