package pe.gob.inei.sistencuesta;

// Generated 15/09/2013 10:46:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RutaPersonal generated by hbm2java
 */
@Entity
@Table(name = "ruta_personal", catalog = "bd_sistencuesta")
public class RutaPersonal implements java.io.Serializable {

	private RutaPersonalId id;
	private Personal personal;
	private Ruta ruta;
	private int numeroEncuestas;
	private String motivoCese;
	private String fechainicio;
	private String fechafin;
	private int nroEncuestasPorDia;
	private int correlativoInicial;
	private String estado;

	public RutaPersonal() {
	}

	public RutaPersonal(RutaPersonalId id, Personal personal, Ruta ruta,
			int numeroEncuestas, int nroEncuestasPorDia,
			int correlativoInicial, String estado) {
		this.id = id;
		this.personal = personal;
		this.ruta = ruta;
		this.numeroEncuestas = numeroEncuestas;
		this.nroEncuestasPorDia = nroEncuestasPorDia;
		this.correlativoInicial = correlativoInicial;
		this.estado = estado;
	}

	public RutaPersonal(RutaPersonalId id, Personal personal, Ruta ruta,
			int numeroEncuestas, String motivoCese, String fechainicio,
			String fechafin, int nroEncuestasPorDia, int correlativoInicial,
			String estado) {
		this.id = id;
		this.personal = personal;
		this.ruta = ruta;
		this.numeroEncuestas = numeroEncuestas;
		this.motivoCese = motivoCese;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.nroEncuestasPorDia = nroEncuestasPorDia;
		this.correlativoInicial = correlativoInicial;
		this.estado = estado;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoPersonal", column = @Column(name = "CodigoPersonal", nullable = false)),
			@AttributeOverride(name = "codigoRuta", column = @Column(name = "CodigoRuta", nullable = false)) })
	public RutaPersonalId getId() {
		return this.id;
	}

	public void setId(RutaPersonalId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoPersonal", nullable = false, insertable = false, updatable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoRuta", nullable = false, insertable = false, updatable = false)
	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	@Column(name = "NumeroEncuestas", nullable = false)
	public int getNumeroEncuestas() {
		return this.numeroEncuestas;
	}

	public void setNumeroEncuestas(int numeroEncuestas) {
		this.numeroEncuestas = numeroEncuestas;
	}

	@Column(name = "MotivoCese", length = 50)
	public String getMotivoCese() {
		return this.motivoCese;
	}

	public void setMotivoCese(String motivoCese) {
		this.motivoCese = motivoCese;
	}

	@Column(name = "fechainicio", length = 10)
	public String getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(String fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Column(name = "fechafin", length = 10)
	public String getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(String fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "NroEncuestasPorDia", nullable = false)
	public int getNroEncuestasPorDia() {
		return this.nroEncuestasPorDia;
	}

	public void setNroEncuestasPorDia(int nroEncuestasPorDia) {
		this.nroEncuestasPorDia = nroEncuestasPorDia;
	}

	@Column(name = "CorrelativoInicial", nullable = false)
	public int getCorrelativoInicial() {
		return this.correlativoInicial;
	}

	public void setCorrelativoInicial(int correlativoInicial) {
		this.correlativoInicial = correlativoInicial;
	}

	@Column(name = "Estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
