package pe.gob.inei.sistencuesta;

// Generated 12/09/2013 09:31:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "cargo", catalog = "bd_sistencuesta")
public class Cargo implements java.io.Serializable {

	private Integer codigoCargo;
	private String nombre;
	private String flagJefatura;
	private Set<Personal> personals = new HashSet<Personal>(0);

	public Cargo() {
	}

	public Cargo(String nombre, String flagJefatura) {
		this.nombre = nombre;
		this.flagJefatura = flagJefatura;
	}

	public Cargo(String nombre, String flagJefatura, Set<Personal> personals) {
		this.nombre = nombre;
		this.flagJefatura = flagJefatura;
		this.personals = personals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoCargo", unique = true, nullable = false)
	public Integer getCodigoCargo() {
		return this.codigoCargo;
	}

	public void setCodigoCargo(Integer codigoCargo) {
		this.codigoCargo = codigoCargo;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "FlagJefatura", nullable = false, length = 1)
	public String getFlagJefatura() {
		return this.flagJefatura;
	}

	public void setFlagJefatura(String flagJefatura) {
		this.flagJefatura = flagJefatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Personal> getPersonals() {
		return this.personals;
	}

	public void setPersonals(Set<Personal> personals) {
		this.personals = personals;
	}

}
