package pe.gob.inei.sistencuesta;

// Generated 17/09/2013 09:30:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MarcoMuestral generated by hbm2java
 */
@Entity
@Table(name = "marco_muestral", catalog = "bd_sistencuesta")
public class MarcoMuestral implements java.io.Serializable {

	private String codigoMarcoMuestral;
	private int año;
	private String descripcion;
	private int numeroEncuestas;
	private String tipoUbigeo;
	private String tipoArea;
	private String estado;
	private Set<Ubigeo> ubigeos = new HashSet<Ubigeo>(0);
	private Set<Encuesta> encuestas = new HashSet<Encuesta>(0);

	public MarcoMuestral() {
	}

	public MarcoMuestral(String codigoMarcoMuestral, int año,
			String descripcion, int numeroEncuestas, String tipoUbigeo,
			String tipoArea, String estado) {
		this.codigoMarcoMuestral = codigoMarcoMuestral;
		this.año = año;
		this.descripcion = descripcion;
		this.numeroEncuestas = numeroEncuestas;
		this.tipoUbigeo = tipoUbigeo;
		this.tipoArea = tipoArea;
		this.estado = estado;
	}

	public MarcoMuestral(String codigoMarcoMuestral, int año,
			String descripcion, int numeroEncuestas, String tipoUbigeo,
			String tipoArea, String estado, Set<Ubigeo> ubigeos,
			Set<Encuesta> encuestas) {
		this.codigoMarcoMuestral = codigoMarcoMuestral;
		this.año = año;
		this.descripcion = descripcion;
		this.numeroEncuestas = numeroEncuestas;
		this.tipoUbigeo = tipoUbigeo;
		this.tipoArea = tipoArea;
		this.estado = estado;
		this.ubigeos = ubigeos;
		this.encuestas = encuestas;
	}

	@Id
	@Column(name = "CodigoMarcoMuestral", unique = true, nullable = false, length = 12)
	public String getCodigoMarcoMuestral() {
		return this.codigoMarcoMuestral;
	}

	public void setCodigoMarcoMuestral(String codigoMarcoMuestral) {
		this.codigoMarcoMuestral = codigoMarcoMuestral;
	}

	@Column(name = "Año", nullable = false)
	public int getAño() {
		return this.año;
	}

	public void setAño(int año) {
		this.año = año;
	}

	@Column(name = "Descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "NumeroEncuestas", nullable = false)
	public int getNumeroEncuestas() {
		return this.numeroEncuestas;
	}

	public void setNumeroEncuestas(int numeroEncuestas) {
		this.numeroEncuestas = numeroEncuestas;
	}

	@Column(name = "TipoUbigeo", nullable = false, length = 1)
	public String getTipoUbigeo() {
		return this.tipoUbigeo;
	}

	public void setTipoUbigeo(String tipoUbigeo) {
		this.tipoUbigeo = tipoUbigeo;
	}

	@Column(name = "TipoArea", nullable = false, length = 1)
	public String getTipoArea() {
		return this.tipoArea;
	}

	public void setTipoArea(String tipoArea) {
		this.tipoArea = tipoArea;
	}

	@Column(name = "Estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "detalle_marco_muestral", catalog = "bd_sistencuesta", joinColumns = { @JoinColumn(name = "CodigoMarcoMuestral", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CodigoUbigeo", nullable = false, updatable = false) })
	public Set<Ubigeo> getUbigeos() {
		return this.ubigeos;
	}

	public void setUbigeos(Set<Ubigeo> ubigeos) {
		this.ubigeos = ubigeos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marcoMuestral")
	public Set<Encuesta> getEncuestas() {
		return this.encuestas;
	}

	public void setEncuestas(Set<Encuesta> encuestas) {
		this.encuestas = encuestas;
	}

}
