package pe.gob.inei.sistencuesta;

// Generated 12/09/2013 09:31:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name = "personal", catalog = "bd_sistencuesta")
public class Personal implements java.io.Serializable {

	private Integer codigoPersonal;
	private Cargo cargo;
	private Ubigeo ubigeo;
	private String nombres;
	private String apellidos;
	private String numeroDocumento;
	private String telefono;
	private String direccion;
	private String estado;
	private Set<RutaPersonal> rutaPersonals = new HashSet<RutaPersonal>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Personal() {
	}

	public Personal(Cargo cargo, Ubigeo ubigeo, String nombres,
			String apellidos, String numeroDocumento, String direccion,
			String estado) {
		this.cargo = cargo;
		this.ubigeo = ubigeo;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.numeroDocumento = numeroDocumento;
		this.direccion = direccion;
		this.estado = estado;
	}

	public Personal(Cargo cargo, Ubigeo ubigeo, String nombres,
			String apellidos, String numeroDocumento, String telefono,
			String direccion, String estado, Set<RutaPersonal> rutaPersonals,
			Set<Usuario> usuarios) {
		this.cargo = cargo;
		this.ubigeo = ubigeo;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.numeroDocumento = numeroDocumento;
		this.telefono = telefono;
		this.direccion = direccion;
		this.estado = estado;
		this.rutaPersonals = rutaPersonals;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoPersonal", unique = true, nullable = false)
	public Integer getCodigoPersonal() {
		return this.codigoPersonal;
	}

	public void setCodigoPersonal(Integer codigoPersonal) {
		this.codigoPersonal = codigoPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoCargo", nullable = false)
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoUbigeo", nullable = false)
	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	@Column(name = "Nombres", nullable = false, length = 50)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "Apellidos", nullable = false, length = 50)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "NumeroDocumento", nullable = false, length = 20)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "Telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "Direccion", nullable = false, length = 100)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "Estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personal")
	public Set<RutaPersonal> getRutaPersonals() {
		return this.rutaPersonals;
	}

	public void setRutaPersonals(Set<RutaPersonal> rutaPersonals) {
		this.rutaPersonals = rutaPersonals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personal")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
