package pe.gob.inei.sistencuesta;

// Generated 13/09/2013 09:04:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pregunta generated by hbm2java
 */
@Entity
@Table(name = "pregunta", catalog = "bd_sistencuesta")
public class Pregunta implements java.io.Serializable {

	private Integer codigoPregunta;
	private Capitulo capitulo;
	private Categoria categoria;
	private Integer numero;
	private Integer nivelPregunta;
	private String descripcion;
	private String tipoPregunta;
	private int longitudDato;
	private String tipoValidacion;
	private String opcional;
	private String respuestaOtros;
	private Set<CedulaRespuesta> cedulaRespuestas = new HashSet<CedulaRespuesta>(
			0);
	private Set<Regla> reglasForCodigoPreguntaOrigen = new HashSet<Regla>(0);
	private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);
	private Set<Regla> reglasForCodigoPreguntaDestino = new HashSet<Regla>(0);

	public Pregunta() {
	}

	public Pregunta(Categoria categoria, String descripcion,
			String tipoPregunta, int longitudDato, String tipoValidacion,
			String opcional) {
		this.categoria = categoria;
		this.descripcion = descripcion;
		this.tipoPregunta = tipoPregunta;
		this.longitudDato = longitudDato;
		this.tipoValidacion = tipoValidacion;
		this.opcional = opcional;
	}

	public Pregunta(Capitulo capitulo, Categoria categoria, Integer numero,
			Integer nivelPregunta, String descripcion, String tipoPregunta,
			int longitudDato, String tipoValidacion, String opcional,
			String respuestaOtros, Set<CedulaRespuesta> cedulaRespuestas,
			Set<Regla> reglasForCodigoPreguntaOrigen,
			Set<Respuesta> respuestas, Set<Regla> reglasForCodigoPreguntaDestino) {
		this.capitulo = capitulo;
		this.categoria = categoria;
		this.numero = numero;
		this.nivelPregunta = nivelPregunta;
		this.descripcion = descripcion;
		this.tipoPregunta = tipoPregunta;
		this.longitudDato = longitudDato;
		this.tipoValidacion = tipoValidacion;
		this.opcional = opcional;
		this.respuestaOtros = respuestaOtros;
		this.cedulaRespuestas = cedulaRespuestas;
		this.reglasForCodigoPreguntaOrigen = reglasForCodigoPreguntaOrigen;
		this.respuestas = respuestas;
		this.reglasForCodigoPreguntaDestino = reglasForCodigoPreguntaDestino;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoPregunta", unique = true, nullable = false)
	public Integer getCodigoPregunta() {
		return this.codigoPregunta;
	}

	public void setCodigoPregunta(Integer codigoPregunta) {
		this.codigoPregunta = codigoPregunta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoCapitulo")
	public Capitulo getCapitulo() {
		return this.capitulo;
	}

	public void setCapitulo(Capitulo capitulo) {
		this.capitulo = capitulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoCategoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@Column(name = "Numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "NivelPregunta")
	public Integer getNivelPregunta() {
		return this.nivelPregunta;
	}

	public void setNivelPregunta(Integer nivelPregunta) {
		this.nivelPregunta = nivelPregunta;
	}

	@Column(name = "Descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "TipoPregunta", nullable = false, length = 2)
	public String getTipoPregunta() {
		return this.tipoPregunta;
	}

	public void setTipoPregunta(String tipoPregunta) {
		this.tipoPregunta = tipoPregunta;
	}

	@Column(name = "LongitudDato", nullable = false)
	public int getLongitudDato() {
		return this.longitudDato;
	}

	public void setLongitudDato(int longitudDato) {
		this.longitudDato = longitudDato;
	}

	@Column(name = "TipoValidacion", nullable = false, length = 2)
	public String getTipoValidacion() {
		return this.tipoValidacion;
	}

	public void setTipoValidacion(String tipoValidacion) {
		this.tipoValidacion = tipoValidacion;
	}

	@Column(name = "Opcional", nullable = false, length = 1)
	public String getOpcional() {
		return this.opcional;
	}

	public void setOpcional(String opcional) {
		this.opcional = opcional;
	}

	@Column(name = "RespuestaOtros", length = 1)
	public String getRespuestaOtros() {
		return this.respuestaOtros;
	}

	public void setRespuestaOtros(String respuestaOtros) {
		this.respuestaOtros = respuestaOtros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pregunta")
	public Set<CedulaRespuesta> getCedulaRespuestas() {
		return this.cedulaRespuestas;
	}

	public void setCedulaRespuestas(Set<CedulaRespuesta> cedulaRespuestas) {
		this.cedulaRespuestas = cedulaRespuestas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preguntaByCodigoPreguntaOrigen")
	public Set<Regla> getReglasForCodigoPreguntaOrigen() {
		return this.reglasForCodigoPreguntaOrigen;
	}

	public void setReglasForCodigoPreguntaOrigen(
			Set<Regla> reglasForCodigoPreguntaOrigen) {
		this.reglasForCodigoPreguntaOrigen = reglasForCodigoPreguntaOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pregunta")
	public Set<Respuesta> getRespuestas() {
		return this.respuestas;
	}

	public void setRespuestas(Set<Respuesta> respuestas) {
		this.respuestas = respuestas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preguntaByCodigoPreguntaDestino")
	public Set<Regla> getReglasForCodigoPreguntaDestino() {
		return this.reglasForCodigoPreguntaDestino;
	}

	public void setReglasForCodigoPreguntaDestino(
			Set<Regla> reglasForCodigoPreguntaDestino) {
		this.reglasForCodigoPreguntaDestino = reglasForCodigoPreguntaDestino;
	}

}
