package pe.gob.inei.sistencuesta;

// Generated 15/09/2013 10:46:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rubro generated by hbm2java
 */
@Entity
@Table(name = "rubro", catalog = "bd_sistencuesta")
public class Rubro implements java.io.Serializable {

	private Integer codigoRubro;
	private String nombre;
	private Set<Encuesta> encuestas = new HashSet<Encuesta>(0);

	public Rubro() {
	}

	public Rubro(String nombre) {
		this.nombre = nombre;
	}

	public Rubro(String nombre, Set<Encuesta> encuestas) {
		this.nombre = nombre;
		this.encuestas = encuestas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoRubro", unique = true, nullable = false)
	public Integer getCodigoRubro() {
		return this.codigoRubro;
	}

	public void setCodigoRubro(Integer codigoRubro) {
		this.codigoRubro = codigoRubro;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rubro")
	public Set<Encuesta> getEncuestas() {
		return this.encuestas;
	}

	public void setEncuestas(Set<Encuesta> encuestas) {
		this.encuestas = encuestas;
	}

}
