package pe.gob.inei.sistencuesta;

// Generated 17/09/2013 09:30:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ruta generated by hbm2java
 */
@Entity
@Table(name = "ruta", catalog = "bd_sistencuesta")
public class Ruta implements java.io.Serializable {

	private Integer codigoRuta;
	private Ubigeo ubigeo;
	private Encuesta encuesta;
	private String numeroRuta;
	private String descripcion;
	private int numeroEncuestas;
	private int correlativoInicial;
	private int correlativoFinal;
	private String estado;
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);
	private Set<Cedula> cedulas = new HashSet<Cedula>(0);
	private Set<RutaPersonal> rutaPersonals = new HashSet<RutaPersonal>(0);

	public Ruta() {
	}

	public Ruta(Ubigeo ubigeo, Encuesta encuesta, String numeroRuta,
			String descripcion, int numeroEncuestas, int correlativoInicial,
			int correlativoFinal, String estado) {
		this.ubigeo = ubigeo;
		this.encuesta = encuesta;
		this.numeroRuta = numeroRuta;
		this.descripcion = descripcion;
		this.numeroEncuestas = numeroEncuestas;
		this.correlativoInicial = correlativoInicial;
		this.correlativoFinal = correlativoFinal;
		this.estado = estado;
	}

	public Ruta(Ubigeo ubigeo, Encuesta encuesta, String numeroRuta,
			String descripcion, int numeroEncuestas, int correlativoInicial,
			int correlativoFinal, String estado,
			Set<Establecimiento> establecimientos, Set<Cedula> cedulas,
			Set<RutaPersonal> rutaPersonals) {
		this.ubigeo = ubigeo;
		this.encuesta = encuesta;
		this.numeroRuta = numeroRuta;
		this.descripcion = descripcion;
		this.numeroEncuestas = numeroEncuestas;
		this.correlativoInicial = correlativoInicial;
		this.correlativoFinal = correlativoFinal;
		this.estado = estado;
		this.establecimientos = establecimientos;
		this.cedulas = cedulas;
		this.rutaPersonals = rutaPersonals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodigoRuta", unique = true, nullable = false)
	public Integer getCodigoRuta() {
		return this.codigoRuta;
	}

	public void setCodigoRuta(Integer codigoRuta) {
		this.codigoRuta = codigoRuta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoUbigeo", nullable = false)
	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoEncuesta", nullable = false)
	public Encuesta getEncuesta() {
		return this.encuesta;
	}

	public void setEncuesta(Encuesta encuesta) {
		this.encuesta = encuesta;
	}

	@Column(name = "NumeroRuta", nullable = false, length = 12)
	public String getNumeroRuta() {
		return this.numeroRuta;
	}

	public void setNumeroRuta(String numeroRuta) {
		this.numeroRuta = numeroRuta;
	}

	@Column(name = "Descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "NumeroEncuestas", nullable = false)
	public int getNumeroEncuestas() {
		return this.numeroEncuestas;
	}

	public void setNumeroEncuestas(int numeroEncuestas) {
		this.numeroEncuestas = numeroEncuestas;
	}

	@Column(name = "CorrelativoInicial", nullable = false)
	public int getCorrelativoInicial() {
		return this.correlativoInicial;
	}

	public void setCorrelativoInicial(int correlativoInicial) {
		this.correlativoInicial = correlativoInicial;
	}

	@Column(name = "CorrelativoFinal", nullable = false)
	public int getCorrelativoFinal() {
		return this.correlativoFinal;
	}

	public void setCorrelativoFinal(int correlativoFinal) {
		this.correlativoFinal = correlativoFinal;
	}

	@Column(name = "Estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rutas")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ruta")
	public Set<Cedula> getCedulas() {
		return this.cedulas;
	}

	public void setCedulas(Set<Cedula> cedulas) {
		this.cedulas = cedulas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ruta")
	public Set<RutaPersonal> getRutaPersonals() {
		return this.rutaPersonals;
	}

	public void setRutaPersonals(Set<RutaPersonal> rutaPersonals) {
		this.rutaPersonals = rutaPersonals;
	}

}
