package pe.gob.inei.sistencuesta;

// Generated 13/09/2013 09:04:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "bd_sistencuesta")
public class Usuario implements java.io.Serializable {

	private String codigoUsuario;
	private Personal personal;
	private Perfil perfil;
	private String nombre;
	private String contraseña;
	private String flagActivo;
	private Set<Cedula> cedulas = new HashSet<Cedula>(0);

	public Usuario() {
	}

	public Usuario(String codigoUsuario, Personal personal, Perfil perfil,
			String nombre, String contraseña, String flagActivo) {
		this.codigoUsuario = codigoUsuario;
		this.personal = personal;
		this.perfil = perfil;
		this.nombre = nombre;
		this.contraseña = contraseña;
		this.flagActivo = flagActivo;
	}

	public Usuario(String codigoUsuario, Personal personal, Perfil perfil,
			String nombre, String contraseña, String flagActivo,
			Set<Cedula> cedulas) {
		this.codigoUsuario = codigoUsuario;
		this.personal = personal;
		this.perfil = perfil;
		this.nombre = nombre;
		this.contraseña = contraseña;
		this.flagActivo = flagActivo;
		this.cedulas = cedulas;
	}

	@Id
	@Column(name = "CodigoUsuario", unique = true, nullable = false, length = 20)
	public String getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(String codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoPersonal", nullable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoPerfil", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "Nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Contraseña", nullable = false, length = 15)
	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

	@Column(name = "FlagActivo", nullable = false, length = 1)
	public String getFlagActivo() {
		return this.flagActivo;
	}

	public void setFlagActivo(String flagActivo) {
		this.flagActivo = flagActivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Cedula> getCedulas() {
		return this.cedulas;
	}

	public void setCedulas(Set<Cedula> cedulas) {
		this.cedulas = cedulas;
	}

}
